team-duck/frontend-duck

- assets/scripts/app.js
- assets/scripts/auth/api.js
- assets/scripts/auth/events.js
- assets/scripts/auth/ui.js
- assets/scripts/config.js
- index.html
- create forms for sign up, sign in, and change password
- create sign out button
- create event listeners for auth events
- add API functions for auth events
- add status messages for successful and failed auth events
- connect app to Heroku backend server
> Feature: Add user authorization features

- assets/scripts/app.js
- assets/scripts/auth/events.js
- assets/scripts/auth/ui.js
- assets/scripts/survey/api.js
- assets/scripts/survey/events.js
- assets/scripts/survey/ui.js
- assets/scripts/templates/create-survey-form.handlebars
- assets/scripts/templates/sign-in-form.handlebars
- assets/scripts/templates/sign-up-form.handlebars
- assets/scripts/templates/survey-controls.handlebars
- assets/scripts/templates/user-controls.handlebars
- index.html
- moved auth forms into Handlebar templates
- moved survey CRUD actions into Handlebar templates
- load components on load and on sign in
> Refactor: Break UI into Handlebar components

- assets/scripts/survey/events.js
- Connected socket.io on the frontend and tested that communication is
happening
- Created specific onSocketIndex handler so that socket calls won't
automatically update the view if you are in the wrong view
> Feature: Connect and test sockets

- assets/scripts/survey/ui.js
- assets/scripts/templates/question-response.handlebars
- assets/scripts/templates/survey-card.handlebars
- assets/scripts/templates/survey-question.handlebars
- index.html
- create Handlebar template and template partials to display surveys
using Bootstrap cards
- create Bootstrap container and row for displaying surveys
> Feature: Add feature to display all surveys

- assets/scripts/auth/events.js
- assets/scripts/auth/ui.js
- assets/scripts/survey/ui.js
- assets/scripts/templates/create-survey-form.handlebars
- assets/scripts/templates/jumbotron.handlebars
- assets/styles/index.scss
Created functional jumbotron
Worked with @nicholaspowel @dnnyp
> Feature jumbotron

- assets/scripts/auth/events.js
- assets/scripts/auth/ui.js
- assets/scripts/templates/auth-accordion.handlebars
- assets/scripts/templates/sign-in-form.handlebars
- assets/scripts/templates/sign-up-form.handlebars
- create new Handlebar template for Bootstrap accordion
- use sign up and sign in templates as partials in accordion template
> Feature: Move auth forms into Bootstrap accordion

- assets/scripts/survey/ui.js
- remove commented out code
- remove unused code
> Refactor: Clean up survey/ui.js

- assets/scripts/survey/ui.js
- assets/scripts/templates/helpers/ownership.js
- assets/scripts/templates/surveys-page/delete.handlebars
- assets/scripts/templates/surveys-page/edit.handlebars
- assets/scripts/templates/surveys-page/survey-preview.handlebars
- assets/scripts/templates/surveys-page/surveys-page.handlebars
Refactored the handlebars for the index call
> Refactor: Survey index views

- assets/scripts/survey/api.js
- assets/scripts/survey/events.js
- assets/scripts/templates/surveys-page/question-response.handlebars
- assets/scripts/templates/surveys-page/survey-card.handlebars
- assets/scripts/templates/surveys-page/survey-question.handlebars
- create API call for answering survey
- create event handler
- update survey card templates
> Feature: Allow users to answer surveys

- assets/scripts/survey/api.js
- assets/scripts/survey/events.js
- assets/scripts/survey/ui.js
- assets/scripts/templates/create-survey/create-survey-form.handlebars
- assets/scripts/templates/create-survey/question-response.handlebars
- assets/scripts/templates/create-survey/update-question.handlebars
- assets/scripts/templates/create-survey/update-survey-form.handlebars
- assets/scripts/templates/main-page/main-body.handlebars
- assets/scripts/templates/main-page/modal.handlebars
- lib/process-survey-data.js
- package-lock.json
- package.json
Created majority of code required to implement survey update
> Feature update

- assets/scripts/auth/events.js
- assets/scripts/auth/ui.js
- assets/scripts/common/messages.js
- assets/styles/index.scss
- assets/styles/theme.scss
- index.html
- package-lock.json
- package.json
Implemented alerts into all authorization actions
> Refactor alerts

- assets/scripts/auth/events.js
Bug fix: Remove the chart when sign-out
> Remove chart on sign out

- assets/styles/index.scss
> Align buttons

- assets/scripts/auth/events.js
- assets/scripts/auth/ui.js
- assets/scripts/survey/ui.js
- assets/scripts/templates/create-survey/create-question-response.handlebars
- assets/scripts/templates/create-survey/create-question.handlebars
- assets/scripts/templates/create-survey/create-survey-modal.handlebars
- assets/scripts/templates/helpers/isActive.js
- assets/scripts/templates/main-page/carousel.handlebars
- assets/scripts/templates/surveys-page/survey-preview.handlebars
- assets/styles/theme.scss
I got the the surveys to show up in the carousel. Still needs styling changes and some code cleanup. Also added handlebars files for create survey in anticipation of implementing the questions and options features.
> Refactor: Add survey previews to carousel

- assets/scripts/common/alerts.js
- assets/scripts/survey/events.js
- assets/scripts/survey/ui.js
- assets/scripts/templates/create-survey/create-survey-modal.handlebars
- assets/scripts/templates/surveys-page/respond-survey-modal.handlebars
Got the submit button on the response to close the modal. 
Also got the results button to show the results view, but have not gotten it to close the modal yet. 
Refactored alerts.js  to allow for suppression of messages. Used this feature in the indexSurvey handler.
> Refactor response

- assets/scripts/auth/events.js
- assets/scripts/survey/events.js
- assets/scripts/survey/ui.js
- assets/scripts/templates/helpers/hasAnswered.js
- assets/scripts/templates/surveys-page/respond-btn.handlebars
- assets/scripts/templates/surveys-page/survey-preview.handlebars
- assets/styles/index.scss
Made respond buttons only work once per user
> Hide respond

- assets/scripts/templates/main-page/jumbotron.handlebars
Reverts team-duck/frontend-duck#40
> Revert "fix typo in jumbotron text"

- assets/scripts/templates/main-page/jumbotron.handlebars
> once more with feeling

- assets/scripts/templates/main-page/jumbotron.handlebars
> Development: Fix typo in jumbotron

- assets/scripts/survey/ui.js
- assets/scripts/templates/nav-bar-content.handlebars
- assets/scripts/templates/splash-page/empty-navbar.handlebars
- index.html
> Bug Fix: response buttons update after click
